### ISSUE TITLE
ph_clean logic should be deprecated

### ISSUE THREAD

**Issue by kentfredric** [gentoo-perl/perl-cleaner#6]
Header files haven't been generated since 5.24 as part of perl itself, and so it doesn't make sense to try purging these if they exist ( they're property of a dedicated package now ).

So, >perl 5.24 , ph files should not be cleaned

Eventually, ph_cleaning should be nuked entirely, but its probably embedded in peoples toolchains/workflows and so it should probably simply become a secret no-op

**Comment by akhuettel** [comment]
This is already done in perl-cleaner-2.28. 

(ph files are still nuked if they are in outdated directories, but that's a different issue and makes sense.)
