### ISSUE TITLE
SONAME search: /usr/lib vs /usr/lib64?

### ISSUE THREAD

**Issue by lkraav** [gentoo-perl/perl-cleaner#8]
I'm not sure what it was earlier, but `dev-lang/perl-5.30.1` installed into `/usr/lib64`

```
leho@gusto / $ qlist perl | grep libperl
/usr/lib64/libperl.so
/usr/lib64/libperl.so.5.30
/usr/lib64/libperl.so.5.30.1
/usr/lib64/perl5/5.30.1/x86_64-linux/CORE/libperl.so
/usr/lib64/perl5/5.30.1/x86_64-linux/CORE/libperl.so.5.30
/usr/lib64/perl5/5.30.1/x86_64-linux/CORE/libperl.so.5.30.1
```

This makes `perl-clean --libperl` endlessly loop libperl-linked packages because `/usr/lib` is hardcoded:

https://github.com/gentoo-perl/perl-cleaner/blob/master/perl-cleaner#L202

Your thoughts?

**Comment by lkraav** [comment]
https://github.com/gentoo-perl/perl-cleaner/blob/master/perl-cleaner#L202 seems to have more problems: `scanelf` fails to get the correct library from `realpath`, if we're trying to match `.{so,dylib}`

```
leho@gusto ~ $ set -x
leho@gusto ~ $ SONAME="$(scanelf -qBS "$(realpath /usr/lib64/libperl.{so,dylib} 2>/dev/null )" | awk '{ print $1 }')"
++ awk '{ print $1 }'
+++ realpath /usr/lib64/libperl.so /usr/lib64/libperl.dylib
++ scanelf -qBS '/usr/lib64/libperl.so.5.30.1
/usr/lib64/libperl.dylib'
+ SONAME=
```

Whereas, let's remove `dylib`:

```
leho@gusto ~ $ SONAME="$(scanelf -qBS "$(realpath /usr/lib64/libperl.so 2>/dev/null )" | awk '{ print $1 }')"
++ awk '{ print $1 }'
+++ realpath /usr/lib64/libperl.so
++ scanelf -qBS /usr/lib64/libperl.so.5.30.1
+ SONAME=libperl.so.5.30
```

**Comment by lkraav** [comment]
Then we also have the quoted magic variable `"@GENTOO_PORTAGE_EPREFIX@"` inside an already quoted string, which will result in a `""` on my system. Seems to still work, but `"something "" something more"` looks dangerous to me.

**Comment by kentfredric** [comment]
> Then we also have the quoted magic variable `"@GENTOO_PORTAGE_EPREFIX@"` inside an already quoted string, which will result in a `""` on my system. Seems to still work, but `"something "" something more"` looks dangerous to me.

That's part of prefix support. It expanding to an empty string on non-prefix targets is what its supposed to do.

And on prefix targets, it must be quoted to avoid whitespace/bashisms in paths breaking things.

https://github.com/gentoo-perl/perl-cleaner/blob/cf024065808205fd11774bf66e6291f1e0f5b1e2/perl-cleaner#L202

https://github.com/gentoo/gentoo/blob/1cc9a7d0c5b62ab36e04c724f5fa6877fb09a88f/app-admin/perl-cleaner/perl-cleaner-2.28.ebuild#L33-L36

https://github.com/gentoo/gentoo/blob/1cc9a7d0c5b62ab36e04c724f5fa6877fb09a88f/app-admin/perl-cleaner/perl-cleaner-2.28.ebuild#L6

https://github.com/gentoo/gentoo/blob/1cc9a7d0c5b62ab36e04c724f5fa6877fb09a88f/eclass/prefix.eclass#L32-L48

**Comment by kentfredric** [comment]
Dear github: Plz be consistent with making permalinks give previews.
